<a href="https://colab.research.google.com/github/IamMarking/Tensorflow/blob/master/CNN_%E5%8D%B7%E7%A7%AF%E7%A5%9E%E7%BB%8F%E7%BD%91%E7%BB%9C.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#### 传统神经网络存在的问题：
- 权值太多，计算量太大，计算起来非常慢
- 权值太多，需要大量样本进行计算

#### 加载数据

In [1]:
import tensorflow as tf

old_v = tf.logging.get_verbosity()
tf.logging.set_verbosity(tf.logging.ERROR)

from tensorflow.examples.tutorials.mnist import input_data

mnist = input_data.read_data_sets("MNIST_data/", one_hot=True)

tf.logging.set_verbosity(old_v)

Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [5]:
batch_size = 100  # 1 次放入 100 张图片进行训练，每张图片维度是 784 维

n_batch = mnist.train.num_examples // batch_size  # 计算一共有多少个批次

# 初始化权值
def weight_variable(shape):
  initial = tf.truncated_normal(shape,stddev=0.1)  # 生成一个截断的正态分布
  return tf.Variable(initial)

# 初始化偏置
def bias_variable(shape):
  initial = tf.constant(0.1,shape=shape)
  return tf.Variable(initial)

# 卷积层
def conv2d(x,W):
  # x 输入的 tensor 的维度 [batch,in_height,in_width,in_channels]
  # 卷积核的 shape [filter_height,filter_width,in_channels,out_channels]
  # 步长第 0 个值和第 3 个值都是 1 ，1 代表 x 方向的步长，2 代表 y 方向的步长
  # padding SAME 补零，VALID 不用补零
  return tf.nn.conv2d(x,W,strides=[1,1,1,1],padding='SAME')  # 2 维的卷积操作，

# 池化层
def max_pool_2x2(x):
  # ksize 窗口的大小，第 1 3 位置设置成 1，中间两个数代表池化窗口大小 2*2
  # 
  return tf.nn.max_pool(x,ksize=[1,2,2,1],strides=[1,2,2,1],padding='SAME')

x = tf.placeholder(tf.float32,[None,784])   
y = tf.placeholder(tf.float32,[None,10])

# 改变 x 的格式转为 4D 的向量 [batch,in_height,in_width,in_channels]
x_image = tf.reshape(x,[-1,28,28,1])

# 初始化第一个卷积层的权值和偏重
W_conv1 = weight_variable([5,5,1,32])  # 5*5 的采样窗口，32 个卷积核从一个平面抽取特征
b_conv1 = bias_variable([32])  # 每一个卷积核一个偏置项

# 把 x_image 和权值向量进行卷积，再加上偏置值，然后应用于 relu 激活函数
h_conv1 = tf.nn.relu(conv2d(x_image,W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1) # 进行 max-pooling 

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    batch_xs,batch_ys = mnist.train.next_batch(batch_size)  # 每 100 张依次进行训练
    print(batch_xs)
    print(batch_xs.shape)
    sess.run(h_conv1,feed_dict={x:batch_xs,y:batch_ys})
    print(x_image.shape)
    print(h_conv1.shape)
    print(h_pool1.shape)
            

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(100, 784)
(?, 28, 28, 1)
(?, 28, 28, 32)
(?, 14, 14, 32)


In [7]:
batch_size = 100  # 1 次放入 100 张图片进行训练，每张图片维度是 784 维

n_batch = mnist.train.num_examples // batch_size  # 计算一共有多少个批次

# 初始化权值
def weight_variable(shape):
  initial = tf.truncated_normal(shape,stddev=0.1)  # 生成一个截断的正态分布
  return tf.Variable(initial)

# 初始化偏置
def bias_variable(shape):
  initial = tf.constant(0.1,shape=shape)
  return tf.Variable(initial)

# 卷积层
def conv2d(x,W):
  # x 输入的 tensor 的维度 [batch,in_height,in_width,in_channels]
  # 卷积核的 shape [filter_height,filter_width,in_channels,out_channels]
  # 步长第 0 个值和第 3 个值都是 1 ，1 代表 x 方向的步长，2 代表 y 方向的步长
  # padding SAME 补零，VALID 不用补零
  return tf.nn.conv2d(x,W,strides=[1,1,1,1],padding='SAME')  # 2 维的卷积操作，

# 池化层
def max_pool_2x2(x):
  # ksize 窗口的大小，第 0 3 位置设置成 1，中间两个数代表池化窗口大小 2*2
  # 
  return tf.nn.max_pool(x,ksize=[1,2,2,1],strides=[1,2,2,1],padding='SAME')

x = tf.placeholder(tf.float32,[None,784])   
y = tf.placeholder(tf.float32,[None,10])

# 改变 x 的格式转为 4D 的向量 [batch,in_height,in_width,in_channels]
x_image = tf.reshape(x,[-1,28,28,1])

# 初始化第一个卷积层的权值和偏重
W_conv1 = weight_variable([5,5,1,32])  # 5*5 的采样窗口，32 个卷积核从一个平面抽取特征
b_conv1 = bias_variable([32])  # 每一个卷积核一个偏置项

# 把 x_image 和权值向量进行卷积，再加上偏置值，然后应用于 relu 激活函数
h_conv1 = tf.nn.relu(conv2d(x_image,W_conv1) + b_conv1)
h_pool1 = max_pool_2x2(h_conv1) # 进行 max-pooling 

# 初始化第二个卷积层的权值和偏重
W_conv2 = weight_variable([5,5,32,64])  # 5*5 的采样窗口，64 个卷积核从 32 个平面抽取特征
b_conv2 = bias_variable([64])  # 每一个卷积核一个偏置项

# 把 x_image 和权值向量进行卷积，再加上偏置值，然后应用于 relu 激活函数
h_conv2 = tf.nn.relu(conv2d(h_pool1,W_conv2) + b_conv2)
h_pool2 = max_pool_2x2(h_conv2) # 进行 max-pooling 


# 28*28 的图片第一次卷积后还是 28*28，第一次池化后变为 14*14，第二次卷积后为 14*14，第二次
# 池化后变为 7*7，经过上面操作后得到 64 张 7*7 的平面

# 初始化第一个全连接层的权值
W_fc1 = weight_variable([7*7*64,1024])  # 上一层有 7*7*64 个神经元，全连接层有 1024 个神经元
b_fc1 = bias_variable([1024])  # 1024 个节点

# 把池化层2的输出扁平化为 1 维
h_pool2_flat = tf.reshape(h_pool2,[-1,7*7*64])
# 求第一个全连接层的输出
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat,W_fc1) + b_fc1)

# keep_prob 用来表示神经元的输出概率
keep_prob = tf.placeholder(tf.float32)
h_fc1_drop = tf.nn.dropout(h_fc1,keep_prob)

# 初始化第二个全连接层
W_fc2 = weight_variable([1024,10])
b_fc2 = bias_variable([10])

# 计算输出
prediction = tf.nn.softmax(tf.matmul(h_fc1_drop,W_fc2) + b_fc2)

# 交叉熵代价函数
cross_entropy = tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(labels=y,logits=prediction))  # 交叉熵损失

train_step = tf.train.AdamOptimizer(1e-4).minimize(cross_entropy)

init = tf.global_variables_initializer()

# 结果存放在一个布尔型变量中
correct_prediction = tf.equal(tf.argmax(y,1), tf.argmax(prediction,1))  # argmax 返回一维张量中最大的值所在的位置

# 求准确率
accuracy = tf.reduce_mean(tf.cast(correct_prediction,tf.float32))  # 转换类型，由布尔型到 float32

with tf.Session() as sess:
    sess.run(init)
    for epoch in range(5):  # 训练 21 次
        for batch in range(n_batch):
            batch_xs,batch_ys = mnist.train.next_batch(batch_size)  # 每 100 张依次进行训练
            sess.run(train_step,feed_dict={x:batch_xs,y:batch_ys,keep_prob:0.7})
        
        acc = sess.run(accuracy,feed_dict={x:mnist.test.images,y:mnist.test.labels,keep_prob:1.0})  # 每一次的准确率变化
        print('Iter ' + str(epoch) + ', Testing Accuracy ' + str(acc))
  

Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

Iter 0, Testing Accuracy 0.9527
Iter 1, Testing Accuracy 0.9711
Iter 2, Testing Accuracy 0.9786
Iter 3, Testing Accuracy 0.9819
Iter 4, Testing Accuracy 0.9842
